import { Product, Category } from "@/types";

const categories: Category[] = [
  {
    id: "cat-1",
    name: "Fashion",
    slug: "fashion",
    description: "Clothing and accessories",
  },
  {
    id: "cat-2",
    name: "Electronics",
    slug: "electronics",
    description: "Gadgets and devices",
  },
  {
    id: "cat-3",
    name: "Groceries",
    slug: "groceries",
    description: "Daily essentials",
  },
  {
    id: "cat-4",
    name: "Home & Kitchen",
    slug: "home-kitchen",
    description: "Appliances and furniture",
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "GTP Nustyle Fabric - Traditional Print (6 Yards)",
    slug: "gtp-nustyle-fabric",
    priceInPesewas: 35000,
    comparePriceInPesewas: 40000,
    image: "https://images.unsplash.com/photo-1616682760884-21915db74026?q=80&w=800&auto=format&fit=crop",
    category: categories[0],
    averageRating: 4.8,
    reviewCount: 12,
    inStock: true,
    isFeatured: true,
    stockQuantity: 50,
    description: "Authentic GTP fabric suitable for all occasions.",
  },
  {
    id: "2",
    name: "Samsung Galaxy A14 (64GB) - Black",
    slug: "samsung-galaxy-a14",
    priceInPesewas: 185000,
    comparePriceInPesewas: undefined,
    image: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?q=80&w=800&auto=format&fit=crop",
    category: categories[1],
    averageRating: 4.5,
    reviewCount: 45,
    inStock: true,
    isFeatured: true,
    stockQuantity: 20,
    description: "Experience the new Galaxy A14 with 64GB storage.",
  },
  {
    id: "3",
    name: "Fresh Pona Yams (Medium Size) - Set of 3",
    slug: "fresh-pona-yams",
    priceInPesewas: 4500,
    image: "https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?q=80&w=800&auto=format&fit=crop",
    category: categories[2],
    averageRating: 4.9,
    reviewCount: 8,
    inStock: true,
    isFeatured: false,
    stockQuantity: 100,
    description: "Farm fresh pona yams directly from the market.",
  },
  {
    id: "4",
    name: "Binatone Blender with Grinder - 1.5L",
    slug: "binatone-blender",
    priceInPesewas: 42000,
    comparePriceInPesewas: 50000,
    image: "https://images.unsplash.com/photo-1570222094114-28a9d88a2b64?q=80&w=800&auto=format&fit=crop",
    category: categories[3],
    averageRating: 4.2,
    reviewCount: 30,
    inStock: true,
    isFeatured: true,
    stockQuantity: 15,
    description: "Powerful blender for all your kitchen needs.",
  },
];
